#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RAILWAY_PUBLIC_DEMO_PROJECT_ID="${RAILWAY_PRODUCTION_PROJECT_ID:-${RAILWAY_PUBLIC_DEMO_PROJECT_ID:-}}"
export RAILWAY_PUBLIC_DEMO_SERVICE="${RAILWAY_PRODUCTION_SERVICE:-${RAILWAY_PUBLIC_DEMO_SERVICE:-}}"
export RAILWAY_PUBLIC_DEMO_WORKER_SERVICE="${RAILWAY_PRODUCTION_WORKER_SERVICE:-${RAILWAY_PUBLIC_DEMO_WORKER_SERVICE:-}}"
export RAILWAY_PUBLIC_DEMO_ENVIRONMENT="${RAILWAY_PRODUCTION_ENVIRONMENT:-${RAILWAY_PUBLIC_DEMO_ENVIRONMENT:-production}}"
export RAILWAY_PUBLIC_DEMO_URL="${RAILWAY_PRODUCTION_URL:-${RAILWAY_PUBLIC_DEMO_URL:-}}"
export RAILWAY_TOKEN="${RAILWAY_PRODUCTION_TOKEN:-${RAILWAY_TOKEN:-}}"
export SHIP_DEMO_EMAIL="${RAILWAY_PRODUCTION_DEMO_EMAIL:-${SHIP_DEMO_EMAIL:-dev@ship.local}}"
export SHIP_DEMO_PASSWORD="${RAILWAY_PRODUCTION_DEMO_PASSWORD:-${SHIP_DEMO_PASSWORD:-admin123}}"
export FLEETGRAPH_SERVICE_TOKEN="${RAILWAY_PRODUCTION_FLEETGRAPH_SERVICE_TOKEN:-${FLEETGRAPH_SERVICE_TOKEN:-}}"
export RAILWAY_DEPLOY_LABEL_PREFIX="${RAILWAY_DEPLOY_LABEL_PREFIX:-production}"

exec "$SCRIPT_DIR/deploy-railway-demo.sh" "$@"
